# Generated by Django 6.0.2 on 2026-02-20 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0003_customer_id_photo'),
        ('lines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SwapSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('STARTED', 'Started'), ('PRIMARY_FAILED', 'Primary Failed'), ('PRIMARY_PASSED', 'Primary Passed'), ('SECONDARY_FAILED', 'Secondary Failed'), ('SECONDARY_PASSED', 'Secondary Passed'), ('FACE_FAILED', 'Face Failed'), ('FACE_PASSED', 'Face Passed'), ('ID_FAILED', 'ID Failed'), ('ID_PASSED', 'ID Passed'), ('COMPLETED', 'Completed'), ('LOCKED', 'Locked')], max_length=50)),
                ('primary_attempts', models.IntegerField(default=0)),
                ('secondary_attempts', models.IntegerField(default=0)),
                ('face_attempts', models.IntegerField(default=0)),
                ('id_attempts', models.IntegerField(default=0)),
                ('is_locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lines.line')),
            ],
        ),
    ]
