# Generated by Django 6.0.2 on 2026-02-21 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swap', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='swapsession',
            name='customer',
        ),
    ]
