# Generated by Django 6.0.2 on 2026-02-25 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swap', '0002_remove_swapsession_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='swapsession',
            name='didit_payload',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='swapsession',
            name='didit_session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='swapsession',
            name='didit_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='swapsession',
            name='stage',
            field=models.CharField(choices=[('STARTED', 'Started'), ('PRIMARY_FAILED', 'Primary Failed'), ('PRIMARY_PASSED', 'Primary Passed'), ('DIDIT_PENDING', 'Didit Pending'), ('DIDIT_FAILED', 'Didit Failed'), ('DIDIT_PASSED', 'Didit Passed'), ('SECONDARY_FAILED', 'Secondary Failed'), ('SECONDARY_PASSED', 'Secondary Passed'), ('FACE_FAILED', 'Face Failed'), ('FACE_PASSED', 'Face Passed'), ('ID_FAILED', 'ID Failed'), ('ID_PASSED', 'ID Passed'), ('COMPLETED', 'Completed'), ('LOCKED', 'Locked')], max_length=50),
        ),
    ]
