# Generated by Django 6.0.2 on 2026-02-28 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swap', '0003_swapsession_didit_payload_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swapsession',
            name='stage',
            field=models.CharField(choices=[('STARTED', 'Started'), ('PRIMARY_FAILED', 'Primary Failed'), ('PRIMARY_PASSED', 'Primary Passed'), ('DIDIT_PENDING', 'Didit Pending'), ('DIDIT_FAILED', 'Didit Failed'), ('DIDIT_PASSED', 'Didit Passed'), ('COMPLETED', 'Completed'), ('LOCKED', 'Locked')], max_length=50),
        ),
    ]
