# Generated by Django 6.0.2 on 2026-02-25 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('event', models.CharField(max_length=255)),
                ('msisdn', models.CharField(max_length=15)),
                ('previous_hash', models.CharField(max_length=256)),
                ('hash', models.CharField(max_length=256)),
            ],
        ),
    ]
