# Generated by Django 6.0.2 on 2026-02-16 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msisdn', models.CharField(max_length=15, unique=True)),
                ('is_golden_number', models.BooleanField(default=False)),
                ('is_whitelisted', models.BooleanField(default=False)),
                ('is_prepaid', models.BooleanField(default=True)),
                ('is_roaming', models.BooleanField(default=False)),
                ('on_in_data', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('IDLE', 'Idle')], max_length=20)),
                ('last_swap_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
            ],
        ),
    ]
