# Generated by Django 6.0.2 on 2026-02-16 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msisdn', models.CharField(max_length=15, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('id_number', models.CharField(max_length=50)),
                ('yob', models.IntegerField()),
                ('iprs_verified', models.BooleanField(default=False)),
                ('iprs_approved', models.BooleanField(default=False)),
                ('fraud_location', models.CharField(choices=[('NORMAL', 'Normal'), ('PRISON_SITE', 'Prison Site'), ('DETACHED', 'Detached')], default='NORMAL', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
