# Generated by Django 6.0.2 on 2026-02-16 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='msisdn',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
