# Generated by Django 6.0.2 on 2026-02-20 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_msisdn'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='id_photo',
            field=models.ImageField(blank=True, null=True, upload_to='user_references/'),
        ),
    ]
