# Generated by Django 6.0.2 on 2026-02-16 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mpesa_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('airtime_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fuliza_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('fuliza_opted_in', models.BooleanField(default=False)),
                ('mshwari_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('mshwari_opted_in', models.BooleanField(default=False)),
                ('kcb_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('kcb_opted_in', models.BooleanField(default=False)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
            ],
        ),
    ]
